#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):
    mpienv = bld.all_envs['mpicc']
    src = '''
        src/tscq.c
        src/mcw.c
    '''

    bld.program(target='mcw', source=src, includes='.. ./src',
                use='M ZLIB', env=mpienv, lib='dbfork_64')
    #bld.program(source='SHMclean.c', target='SHMclean', env=mpienv)
    #bld.program(source='wrap.c', target='wrap', env=mpienv)
