#!/usr/bin/env python

def build(bld):
    src = '''
    src/process_control.c
    '''

    ## user libraries
    bld.stlib(target='hsp', source=src, includes='.',
              export_includes='.', use='PTHREAD')
