#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):
    mpienv = bld.all_envs['mpicc']

    tests = [
        'test-fgetc',
        'test-fgets',
        'test-db',
        'test-kill',
        'test-fasta',
    ]

    for t in tests:
        bld.program(source='{0}.c'.format(t), target=t,
                    use='stdiowrap', lib='rt')

