#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):

    # objects
    # TODO: make filesize_t opaque so we don't need BACKEND_SHM everywhere.
    bld.objects(source='filebufwrap.cpp', target='filebufwrap',
            features='cxx', defines='BACKEND_SHM')
    bld.objects(source='fstreamwrap.cpp', target='fstreamwrap',
            features='cxx', defines='BACKEND_SHM')
    bld.objects(source='streambufwrap.cpp', target='streambufwrap',
            features='cxx', defines='BACKEND_SHM')

    ## user libraries
    bld.stlib(source='stdiowrap.c', target='stdiowrap', defines='BACKEND_SHM')

    bld.new_task_gen(target='stdiowrap++', use='stdiowrap filebufwrap fstreamwrap',
                features='cxx cxxstlib', defines='BACKEND_SHM')

