#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):
    src = '''
        src/strutils.c
    '''

    ## user library
    bld.stlib(target='strutils', source=src, includes='.',
              export_includes='.')
