.TH GATHER "1" "December 2011" "MCW Tools" "User Commands"
.SH NAME
gather \- gather and decompress a job's results into a single listing
.SH SYNOPSIS
.B gather
\fIDIR\fR
.SH DESCRIPTION
.\" Add any additional description here
.PP
Gathers all standard output contained in \fIDIR\fR, decompressing if needed.
The resulting data is writen to standard output.
.PP
Exit status is 0 if OK, 1 if problems.
.SH AUTHOR
Written by Paul Giblock.
.SH "REPORTING BUGS"
Report bugs to <pgiblock@utk.edu>.
.SH COPYRIGHT
Copyright \(co 2011 (TODO: Pick a license)
