.TH XMLPARSE "1" "December 2011" "MCW Tools" "User Commands"
.SH NAME
xmlparse \- parse blastall XML output into a condensed format
.SH SYNOPSIS
.B xmlparse
\fIXMLFILE\fR
.SH DESCRIPTION
.\" Add any additional description here
.PP
Parses and condenses the data from \fIXMLFILE\fR, created
when the \fB-m 7\fR option is given to the \fBblastall\fR utility.
The resulting data is writen to standard output.
.PP
Exit status is 0 if OK, non-zero if problems.
.SH AUTHOR
Written by Paul Giblock and Aaron Vose.
.SH "REPORTING BUGS"
Report bugs to <pgiblock@utk.edu>.
.SH COPYRIGHT
Copyright \(co 2011 (TODO: Pick a license)
