#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):
    mpienv = bld.all_envs['mpicc']

    bld.program(source='src/hspwrap.c', target='hspwrap',
                use='YAML PTHREAD')

    bld.program(source='src/hspwrap-ev.c', target='hspwrap-ev',
                use='YAML ev PTHREAD M')

    #bld.program(target='hspwrap', source=src, 'src',
    #            use='M', env=mpienv)

    bld.recurse('libev-4.15')
