#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):
    mpienv = bld.all_envs['mpicc']

    bld.program(source='src/hspwrap.c src/process_pool.c', target='hspwrap',
                use='hsp YAML PTHREAD', env=mpienv, lib='rt')

    #bld.program(lib='rt', source='src/hspwrap-ev.c', target='hspwrap-ev',
    #            use='hsp YAML ev PTHREAD M')

    #bld.recurse('libev-4.15')
