#!/usr/bin/env python

def build(bld):
    c_src = '''
        src/stdiowrap.c
    '''
    cpp_src = '''
        src/filebuf.cpp
        src/fstream.cpp
        src/ifstream.cpp
        src/ofstream.cpp
        src/streambuf.cpp
    '''

    ## user libraries
    bld.stlib(target='stdiowrap', source=c_src, includes='.',
              export_includes='.', defines='BACKEND_SHM',
	      use='hsp PTHREAD', lib='rt')

    bld.new_task_gen(target='stdiowrap++', source=cpp_src, includes='.',
                     use='stdiowrap', features='cxx cxxstlib',
                     export_includes='.', defines='BACKEND_SHM')

