#!/bin/bash
#PBS -N example-job
#PBS -l walltime=0:30:00,size=24
#PBS -q small
#PBS -v MCWDIR,MCW_DB_PATH,MCW_DB_COUNT,MCW_DB_PREFIX,MCW_DB_FILES

# Node count.  Make sure -l size=NODES*CORES above!
NODES="2"
# Core count.  Keep at 12 for Kraken.
CORES="12"

# Time limit.  Make sure equals minutes of -l walltime above!
TIMEM="30"

# Command line, make sure to use blastp or blastn as appropriate.
CMD_LINE="--domtblout :OUT: :DB: :IN:"

# Input query file
Q_FILE="$MCWDIR/share/doc/input/sample-24.fasta"

# Block size (bytes)
BLOCK_SIZE=10

#####################################################################
# You shouldn't need to edit anything below this point.
#####################################################################


BINDIR="$MCWDIR/bin"
LIBDIR="$MCWDIR/lib/mcw"

cd $PBS_O_WORKDIR

TIME=$(( ( TIMEM - 3 ) * 60 ));

export MCW_JOB_NAME="$PBS_JOBID"

### Database Settings
# Set MCW_DB_PATH, MCW_DB_COUNT, MCW_DB_PREFIX, and MCW_DB_FILES to override
# currently loaded db module.

### Input / Query Settings
### Compression (Or at least blocking) is required at the moment

export MCW_Q_FILE=".mcw-$PBS_JOBID.tmp"
export MCW_Q_WUM="1"
$BINDIR/compressfasta0 $Q_FILE $BLOCK_SIZE $MCW_Q_FILE

### Search Settings

export MCW_S_TIMELIMIT="$TIME"
export MCW_S_EXE="$LIBDIR/hmmscan"
export MCW_S_LINE="$CMD_LINE"
export MCW_S_DUP2=""

# Run the computational job
ulimit -c unlimited -f unlimited
time aprun -n $NODES -N 1 -d $CORES $BINDIR/mcw > /dev/null

