#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):

    # FASTA tools
    for t in ['fastalens', 'fastadist', 'splitfasta', 'sortfasta']:
        bld.program(source='%s.c'%t, target=t)

    bld.program(source='compressfasta.c', target='compressfasta',
            use='version zutils', defines='CF_COMPRESSION_LEVEL=Z_DEFAULT_COMPRESSION')
    bld.program(source='compressfasta.c', target='compressfasta0',
            use='version zutils', defines='CF_COMPRESSION_LEVEL=Z_NO_COMPRESSION')
    bld.program(source='splitfasta.c', target='splitfasta')

    # MOL2 tools
    bld.program(source='compressmol2.c', target='compressmol2', use='zutils')
    bld.program(source='splitmol2.c', target='splitmol2')

    # Block-wise recovery
    bld.program(source='recover.c', target='recover', use='ioutils version')

    # Special tools
    bld.program(source='gather.c', target='gather', use='ioutils strutils version zutils')
    bld.program(source='xmlparse.c', target='xmlparse', use='EXPAT')
    bld.program(source='zextract.c', target='zextract', use='zutils')
    bld.program(source='zsplit.c', target='zsplit', use='ioutils version')
    bld.program(source='zstat.c', target='zstat', use='zutils')

    # MPI apps
    mpienv = bld.all_envs['mpicc']
    bld.objects(source='tscq.c', target='tscq', env=mpienv)
    bld.program(source='mcw.c', includes='. ../..', target='mcw', use='M ZLIB tscq', env=mpienv)
    #bld.program(source='SHMclean.c', target='SHMclean', env=mpienv)
    #bld.program(source='wrap.c', target='wrap', env=mpienv)
