#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):

    # Libraries
    bld.stlib(source='zutils.c', target='zutils', use='ZLIB')
    bld.stlib(source='strutils.c', target='strutils')

    # FASTA tools
    for t in ['fastalens', 'fastadist', 'splitfasta', 'sortfasta']:
        bld.program(source='%s.c'%t, target=t)

    bld.program(source='compressfasta.c', target='compressfasta',
            use='zutils', defines='CF_COMPRESSION_LEVEL=Z_DEFAULT_COMPRESSION')
    bld.program(source='compressfasta.c', target='compressfasta0',
            use='zutils', defines='CF_COMPRESSION_LEVEL=Z_NO_COMPRESSION')
    bld.program(source='recoverfasta.cc', target='recoverfasta',
            features='cxx cxxprogram')

    # MOL2 tools
    bld.program(source='splitmol2.c', target='splitmol2')
    bld.program(source='compressmol2.c', target='compressmol2', use='zutils')
    bld.program(source='recovermol2.cc', target='recovermol2',
            features='cxx cxxprogram')

    # Special tools
    bld.program(source='gather.c', target='gather', use='zutils strutils')
    bld.program(source='xmlparse.c', target='xmlparse', use='EXPAT')
    bld.program(source='zextract.c', target='zextract', use='zutils')
    bld.program(source='zstat.c', target='zstat', use='zutils')

    # MPI apps
    mpienv = bld.all_envs['mpicc']
    bld.objects(source='tscq.c', target='tscq', env=mpienv)
    bld.program(source='mcw.c', includes='. ../..', target='mcw', use='M ZLIB tscq', env=mpienv)
    #bld.program(source='SHMclean.c', target='SHMclean', env=mpienv)
    #bld.program(source='wrap.c', target='wrap', env=mpienv)
