#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):

    # FASTA tools
    for t in ['fastalens', 'fastadist', 'splitfasta', 'sortfasta']:
        bld.program(source='%s.c'%t, target=t)

    bld.program(source='compressfasta.c', target='compressfasta',
            use='ZLIB', defines='CF_COMPRESSION_LEVEL=Z_DEFAULT_COMPRESSION')
    bld.program(source='compressfasta.c', target='compressfasta0',
            use='ZLIB', defines='CF_COMPRESSION_LEVEL=Z_NO_COMPRESSION')
    bld.program(source='recoverfasta.cc', target='recoverfasta',
            features='cxx cxxprogram')

    # MOL2 tools
    bld.program(source='splitmol2.c', target='splitmol2')
    bld.program(source='compressmol2.c', target='compressmol2', use='ZLIB')
    bld.program(source='recovermol2.cc', target='recovermol2',
            features='cxx cxxprogram')

    # Special tools
    bld.program(source='xmlparse.c', target='xmlparse', use='EXPAT')
    bld.program(source='zextract.c', target='zextract', use='ZLIB')

    # MCW stuff
    bld.stlib(source='tscq.c', target='tscq')
    
    #TODO: Needs MPI
    #bld.program(source='mcw.c', target='mcw', use='ZLIB tscq')
    #bld.program(source='SHMclean.c', target='SHMclean')
    #bld.program(source='wrap.c', target='wrap')
